spring:
  config:
    activate:
      on-profile: default
#eureka:
#  instance:
    # enable to register multiple app instances with a random server port
    #instance-id: ${spring.application.name}:${random.uuid}
#    preferIpAddress: true
eureka:
    instance:
        prefer-ip-address: true
        ip-address: ${server.address}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
